name: Waka Time Stats

on:
  workflow_dispatch:
  schedule:
    # every minute
    - cron: '* * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: enkr1/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: TRUE
          SHOW_SHORT_INFO: TRUE
          SHOW_PROFILE_VIEWS: TRUE
          SHOW_LOC_CHART:  TRUE
          SHOW_PROJECTS:  FALSE
